spring.application.name=the-thinker

spring.datasource.name=${DB_NAME:thinker}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/thinker}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
#I want to run the schema sql
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.datasource.initialization-mode=always
